### ISSUE TITLE
Repository namespace does not being consider

### ISSUE THREAD

**Issue by kidzen** [Rekamy/ApiGenerator#1]
Version : v1.0.2

How To:
1. change config/apigenerator.php
```
'namespace' => [
        ...
        'repository'            => 'App\Repositories\Base',
        ...
    ],
```

Result:
Namepace repository generated does not respect config.

**Comment by kidzen** [comment]
This also effect controller generated namespace

**Comment by firdausishaddin** [comment]
closed as it has been fixed.

thank you for your feedback
